steps:
  # Clone the repository and configure credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git unzip
        git config --global init.defaultBranch main
        git branch -m main
        echo "$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")" | gh auth login --with-token
        echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > /credentials.json 
        gcloud auth activate-service-account --key-file=/credentials.json
        gcloud auth list
        gcloud config list
        gsutil cp gs://protech_bucket/nupack-4.0.1.12.zip /workspace/nupack-4.0.1.12.zip 
        unzip /workspace/nupack-4.0.1.12.zip -d /workspace/nupack-4.0.1.12
        rm /workspace/nupack-4.0.1.12.zip
        ls /workspace/nupack-4.0.1.12

 # Install Miniconda and Nupack
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget g++
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda3
        /miniconda3/bin/conda update -n base -c defaults conda
        rm Miniconda3-latest-Linux-x86_64.sh
        /miniconda3/bin/conda install numpy scipy pip matplotlib pandas jupyterlab
        ls /workspace/nupack-4.0.1.12
        /miniconda3/bin/pip install -U nupack -f /workspace/nupack-4.0.1.12/nupack-4.0.1.12/package
        /miniconda3/bin/pip install -r requirements.txt
        /miniconda3/bin/activate base
        /miniconda3/bin/python tool/server.py

options:
  logging: CLOUD_LOGGING_ONLY  
