steps:
  # Clone the repository and configure credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git unzip
        git config --global init.defaultBranch main
        git branch -m main
        gcloud config set project protech-new-435412
        echo "$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")" | gh auth login --with-token
        echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > /credentials.json 
        gcloud auth activate-service-account --key-file=/credentials.json
        gsutil cp gs://protech_bucket/nupack-4.0.1.12.zip /workspace/nupack-4.0.1.12.zip 
        unzip /workspace/nupack-4.0.1.12.zip -d /workspace
        rm /workspace/nupack-4.0.1.12.zip

  # Install Miniconda and NUPACK
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget g++
        cd /workspace
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        /bin/bash /workspace/Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda3
        /miniconda3/bin/conda update -c defaults conda
        rm Miniconda3-latest-Linux-x86_64.sh
        /miniconda3/bin/conda create -n myenv python=3.9 -y
        source /miniconda3/bin/activate myenv
        /miniconda3/bin/conda config --add channels defaults
        /miniconda3/bin/conda config --add channels bioconda
        /miniconda3/bin/conda config --add channels conda-forge
        /miniconda3/bin/conda config --set channel_priority strict
        /miniconda3/bin/conda install bioconda numpy scipy pip matplotlib pandas jupyterlab        
        /miniconda3/bin/conda install viennarna
        /miniconda3/bin/pip install -U nupack -f /workspace/nupack-4.0.1.12/package
        /miniconda3/bin/pip install gunicorn biopython flask wtforms flask_wtf werkzeug google-cloud-storage tqdm numpy scipy pip matplotlib pandas jupyterlab viennaRNA
        
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/protech-new-435412/software', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/protech-new-435412/software']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'software'
    - '--image'
    - 'gcr.io/protech-new-435412/software'
    - '--region'
    - 'us-central1'
    
  images:
  - 'gcr.io/protech-new-435412/software'
  
options:
  logging: CLOUD_LOGGING_ONLY  
