steps:
  # Retrieve the GitHub token from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install GitHub CLI (gh) if not already available
        apt-get update && apt-get install -y gh

        # Authenticate with GitHub CLI
        GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=GITHUB_TOKEN)

        # Authenticate with GitHub CLI using the retrieved token
        echo "$GITHUB_TOKEN" | gh auth login --with-token

  # Decode the base64 CREDENTIALS_JSON environment variable and save it as credentials.json
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "{{ env.CREDENTIALS_JSON }}" | base64 --decode > credentials.json
        
  # Activate the service account using the credentials.json
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=credentials.json
        gcloud auth list
        gcloud config list

  # Build the Docker image with the credentials JSON as a build argument
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CREDENTIALS_JSON=${env.CREDENTIALS_JSON}'
      - '-t'
      - 'gcr.io/spry-ivy-431810-v0/protech'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/spry-ivy-431810-v0/protech'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nupack-app'
      - '--image'
      - 'gcr.io/spry-ivy-431810-v0/protech'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/spry-ivy-431810-v0/protech'

options:
  logging: CLOUD_LOGGING_ONLY
