steps:
  # Clone the repository to get the credentials.json file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install git if necessary
        apt-get update && apt-get install -y git

        # Clone the repository to get credentials.json
        git clone https://github.com/talshem/software.git /workspace/repo
        cp /workspace/repo/credentials.json /workspace/credentials.json

  # Activate the service account using the credentials.json
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=/workspace/credentials.json
        gcloud auth list
        gcloud config list

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/spry-ivy-431810-v0/protech'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/spry-ivy-431810-v0/protech'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nupack-app'
      - '--image'
      - 'gcr.io/spry-ivy-431810-v0/protech'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/spry-ivy-431810-v0/protech'

options:
  logging: CLOUD_LOGGING_ONLY
