steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/spry-ivy-431810-v0/protech', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/spry-ivy-431810-v0/protech']
images:
  - 'gcr.io/spry-ivy-431810-v0/protech'

  steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/spry-ivy-431810-v0/protech', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/spry-ivy-431810-v0/protech']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'nupack-app', '--image', 'gcr.io/spry-ivy-431810-v0/protech', '--platform', 'managed', '--region', 'us-central1']

images:
  - 'gcr.io/$PROJECT_ID/nupack-app'
options:
  logging: CLOUD_LOGGING_ONLY

