steps:
  # Clone the repository and configure credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git unzip gh
        echo "$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")" | gh auth login --with-token
        echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > credentials.json 

  # Activate the service account using credentials.json
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=credentials.json
        gcloud auth list
        gcloud config list

  # Install Python requirements and NUPACK
  - name: 'python:3.9-slim-buster'
    id: 'Install NUPACK and Dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        gsutil cp gs://protech_bucket/nupack-4.0.1.12.zip /app/nupack-4.0.1.12.zip
        unzip nupack-4.0.1.12.zip
        cd nupack-4.0.1.12
        pip install -U nupack -f ./package

  # Run server.py
  - name: 'python:3.9-slim-buster'
    id: 'Run Server'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python tool/server.py

options:
  logging: CLOUD_LOGGING_ONLY 
