steps:
  # Clone the repository and configure credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git gh unzip
        git config --global init.defaultBranch main
        git branch -m main
        echo "$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")" | gh auth login --with-token
        echo "$CREDENTIALS_JSON" | base64 -d > /credentials.json 
        gcloud auth activate-service-account --key-file=/credentials.json
        gcloud auth list
        gcloud config list
        gsutil cp gs://protech_bucket/nupack-4.0.1.12.zip /workspace/nupack-4.0.1.12.zip 
        unzip /workspace/nupack-4.0.1.12.zip -d /workspace
        rm /workspace/nupack-4.0.1.12.zip
        ls /workspace/nupack-4.0.1.12

 # Install Miniconda and Nupack
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget g++
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /workspace
        /bin/bash /workspace/Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda3
        /miniconda3/bin/conda update -c defaults conda
        rm Miniconda3-latest-Linux-x86_64.sh
        /miniconda3/bin/conda create -n /workspace/myenv python=3.9 -y
        source /miniconda3/bin/activate /workspace/myenv
        /miniconda3/bin/conda install numpy scipy pip matplotlib pandas jupyterlab
        ls /workspace/nupack-4.0.1.12
        /miniconda3/bin/pip install --target=/workspace/myenv/lib/python3.8/site-packages -U nupack -f /workspace/nupack-4.0.1.12/package
        /miniconda3/bin/pip install --target=/workspace/myenv/lib/python3.9/site-packages biopython flask wtforms flask_wtf werkzeug google-cloud-storage tqdm numpy scipy pip matplotlib pandas jupyterlab viennaRNA
        python /workspace/tool/server.py

options:
  logging: CLOUD_LOGGING_ONLY  
