steps:
  # Clone the repository and configure credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git branch -m main
        apt-get update && apt-get install -y git unzip
        echo "$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")" | gh auth login --with-token
        echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > /credentials.json 
        gcloud auth activate-service-account --key-file=/credentials.json
        gcloud auth list
        gcloud config list
        gsutil cp gs://protech_bucket/nupack-4.0.1.12.zip /nupack-4.0.1.12.zip 
        unzip /nupack-4.0.1.12.zip -d /nupack-4.0.1.12
        rm /nupack-4.0.1.12.zip

   - name: 'python:3.10-slim-buster'
    id: 'Install NUPACK'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install biopython
        
  - name: 'python:3.9-slim-buster'
    id: 'Install NUPACK'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements9.txt
        pip install -U nupack -f /nupack-4.0.1.12/package
        python tool/server.py
        
options:
  logging: CLOUD_LOGGING_ONLY 
