steps:
  # Clone the repository and configure credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git branch -m main
        apt-get update && apt-get install -y git unzip
        echo "$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")" | gh auth login --with-token
        echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > /credentials.json 
        gcloud auth activate-service-account --key-file=/credentials.json
        gcloud auth list
        gcloud config list
        gsutil cp gs://protech_bucket/nupack-4.0.1.12.zip /nupack-4.0.1.12.zip 
        unzip /nupack-4.0.1.12.zip -d /nupack-4.0.1.12
        rm /nupack-4.0.1.12.zip

 # Step 1: Install Miniconda
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        /bin/bash Miniconda3-latest-Linux-x86_64.sh -b
        miniconda3/bin/conda update -n base -c defaults conda
        rm Miniconda3-latest-Linux-x86_64.sh

        export PATH=$HOME/miniconda3/bin:$PATH
        echo 'export PATH=$HOME/miniconda3/bin:$PATH' >> ~/.bashrc

        conda install numpy scipy pip matplotlib pandas jupyterlab
        pip install -U nupack -f ./nupack-4.0.1.12/package

  - name: 'python:3.9-slim-buster'
    id: 'Install dependencies and run server'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python tool/server.py
        
options:
  logging: CLOUD_LOGGING_ONLY 
