steps:
  # Retrieve the GitHub token from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install GitHub CLI (gh) if not already available
        apt-get update && apt-get install -y gh

        # Retrieve the GitHub token from Secret Manager
        GITHUB_TOKEN=$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")
        
        # Authenticate with GitHub CLI
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

        # Retrieve the base64-encoded secret from GitHub
        SECRET_BASE64=$(gh secret view CREDENTIALS_JSON --repo talshem/software --json value -q '.value')

        # Decode the base64 secret and save it as credentials.json
        echo "$SECRET_BASE64" | base64 --decode > credentials.json

  # Build the Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CREDENTIALS_JSON=./credentials.json'
      - '-t'
      - 'gcr.io/spry-ivy-431810-v0/protech'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/spry-ivy-431810-v0/protech'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nupack-app'
      - '--image'
      - 'gcr.io/spry-ivy-431810-v0/protech'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/spry-ivy-431810-v0/protech'

options:
  logging: CLOUD_LOGGING_ONLY
